using System.Diagnostics;
using Content.Shared.CraftingSystem;
using Content.Shared.Item;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.CraftingSystem.UI;


[GenerateTypedNameReferences]
public sealed partial class CraftingMenuEntry : ContainerButton
{
    public CraftingRecipePrototype? Recipe;
    public bool isHandheld = false;
    public event Action<CraftingRequestReceivedArgs>? OnCraftRequest;


    public CraftingMenuEntry()
    {
        RobustXamlLoader.Load(this);
        DrawModeChanged();
    }

    public void InitFromRecipe(CraftingRecipePrototype? recipePrototype, IPrototypeManager prototypeManager)
    {
        Recipe = recipePrototype;

        if (recipePrototype == null || Recipe?.OutputId == null)
        {
            return;
        }

        if (!prototypeManager.TryIndex(Recipe.OutputId, out var outputItem))
        {
            DebugTools.Assert(Recipe.OutputId == string.Empty || Recipe.OutputId.Length <= 0,  $"OutputID: {Recipe.OutputId} is an empty string. Perhaps you forgot to set it? Recipe was {Recipe.ID}.");
            Parent?.RemoveChild(this);
            return;
        }

        NameLabel.Text = Recipe?.Name;
        if (outputItem.Components.TryGetValue("sprite", out var spriteComponent))
        {
            if (spriteComponent.Component is SpriteComponent outputSprite)
            {
                Icon.Texture =  outputSprite.Icon?.Default;
            }
        }

        if (outputItem.Components.TryGetValue("Item", out var itemComponent))
        {
            isHandheld = itemComponent.Component is ItemComponent;
        }


        OnPressed += RequestCraft;

    }


    public void RequestCraft(ButtonEventArgs args)
    {
        if (Recipe == null)
            return;

        OnCraftRequest?.Invoke(new CraftingRequestReceivedArgs(Recipe.ID));
    }
}
