using System.Numerics;
using Content.Shared.CraftingSystem;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.CraftingSystem.UI;

public interface  ICraftingMenuUI : IDisposable
{
    string[] Categories { get; set; }
    ItemList Recipes { get; }

    IPrototypeManager prototypeManager { get; }
    event EventHandler<(string search, string category, string materialFilter)> PopulateRecipes;

    public void Dispose()
    {
        throw new NotImplementedException();
    }
}
[GenerateTypedNameReferences]
public sealed partial class CraftingMenu : DefaultWindow, ICraftingMenuUI
{

    public string[] Categories { get; set; } =  Array.Empty<string>();
    public ItemList Recipes { get; set; } = new ItemList();
    public IPrototypeManager prototypeManager { get; }
    public CraftingMenuPresenter? Presenter;
    public event EventHandler<(string search, string category, string materialFilter)>? PopulateRecipes;

    public CraftingRecipePrototype? selectedRecipe { get; set; }

    public CraftingMenu(IPrototypeManager prototypeManager)
    {
        this.prototypeManager = prototypeManager;
        SetSize = new Vector2(560, 450);
        MinSize = new Vector2(560, 320);


        // Using ConstructionMenu as a guide here, do I fully understand everything here? No.
        // Do I understand what I need to? Contentious.
        // but I'm coding either way.
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        Title = Loc.GetString("construction-menu-title");

        // TODO: as we get buttons, fill out events BELOW HERE but we haven't a UI and haven't any buttons.

        // TODO: that concludes events.


        tabsContainer.SetTabTitle(0, Loc.GetString("crafting-system-category-common"));
        tabsContainer.SetTabTitle(1, Loc.GetString("crafting-system-category-structure"));

    }

    public void SpawnEntries(List<CraftingRecipePrototype> craftingRecipes)
    {
        EntryHolder.RemoveAllChildren();
        // I've been told this works. Dispose was deprecated. Maybe a memory leak. May work fine.
        foreach (var recipe in craftingRecipes)
        {
            var entry = new CraftingMenuEntry();
            if (Parent != null) // I don't recall if this is automated.
            {
                EntryHolder.AddChild(entry);
            }
            entry.InitFromRecipe(recipe, prototypeManager);
            entry.OnCraftRequest += _ => Presenter?.GetCraftingSystem?.CraftingRequestHandler(entry);
        }
    }

}
