using Content.Shared.CraftingSystem;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.CraftingSystem.UI;


[GenerateTypedNameReferences]
public sealed partial class CraftingMenuEntry : ContainerButton
{
    public CraftingRecipePrototype? Recipe;

    public void InitFromRecipe(CraftingRecipePrototype? recipePrototype)
    {
        Recipe = recipePrototype;
        if (recipePrototype == null)
        {

        }
    }
}
