using System.Numerics;
using Content.Shared.CraftingSystem;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CraftingSystem.UI;

public interface  ICraftingMenuUI : IDisposable
{
    string[] Categories { get; set; }
    ItemList Recipes { get; }


    public void Dispose()
    {
        throw new NotImplementedException();
    }
}
[GenerateTypedNameReferences]
public sealed partial class CraftingMenu : DefaultWindow, ICraftingMenuUI
{


    public string[] Categories { get; set; } =  Array.Empty<string>();
    public ItemList Recipes { get; set; } = new ItemList();

    public CraftingRecipePrototype selectedRecipe { get; set; }

    event EventHandler<(string search, string category, string materialFilter)> PopulateRecipes;
    public CraftingMenu()
    {
        SetSize = new Vector2(560, 450);
        MinSize = new Vector2(560, 320);


        // Using ConstructionMenu as a guide here, do I fully understand everything here? No.
        // Do I understand what I need to? Contentious.
        // but I'm coding either way.
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        // TODO: as we get buttons, fill out events BELOW HERE but we haven't a UI and haven't any buttons.

        // TODO: that concludes events.



    }




}
